### ISSUE TITLE
(IMPORTANT) add logos for Raytheon and IBM on index.html page at the bottom

### ISSUE THREAD

**Issue by anshulgandhi1** [middleware2017/middleware2017.repo#3]
Similar to 2016. So far, we have IBM and Raytheon BBN.

**Comment by Jasim9** [comment]
Is the sponsor IBM or IBM Research?

**Comment by anshulgandhi1** [comment]
IBM Research.

**Comment by Jasim9** [comment]
Added IBM and Raytheon, will close this issue when complete list is done.
